# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/transactionservices.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import transrequestmesg_pb2 as protos_dot_transrequestmesg__pb2
from protos import transresponsemesg_pb2 as protos_dot_transresponsemesg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/transactionservices.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n protos/transactionservices.proto\x1a\x1dprotos/transrequestmesg.proto\x1a\x1eprotos/transresponsemesg.proto2L\n\x13TransactionServices\x12\x35\n\ngetBalance\x12\x11.TransRequestMesg\x1a\x12.TransResponseMesg\"\x00\x62\x06proto3'
  ,
  dependencies=[protos_dot_transrequestmesg__pb2.DESCRIPTOR,protos_dot_transresponsemesg__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TRANSACTIONSERVICES = _descriptor.ServiceDescriptor(
  name='TransactionServices',
  full_name='TransactionServices',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=99,
  serialized_end=175,
  methods=[
  _descriptor.MethodDescriptor(
    name='getBalance',
    full_name='TransactionServices.getBalance',
    index=0,
    containing_service=None,
    input_type=protos_dot_transrequestmesg__pb2._TRANSREQUESTMESG,
    output_type=protos_dot_transresponsemesg__pb2._TRANSRESPONSEMESG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSACTIONSERVICES)

DESCRIPTOR.services_by_name['TransactionServices'] = _TRANSACTIONSERVICES

# @@protoc_insertion_point(module_scope)
