# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/transresponsemesg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/transresponsemesg.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1eprotos/transresponsemesg.proto\"#\n\x11TransResponseMesg\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\x62\x06proto3'
)




_TRANSRESPONSEMESG = _descriptor.Descriptor(
  name='TransResponseMesg',
  full_name='TransResponseMesg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='TransResponseMesg.amount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['TransResponseMesg'] = _TRANSRESPONSEMESG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransResponseMesg = _reflection.GeneratedProtocolMessageType('TransResponseMesg', (_message.Message,), {
  'DESCRIPTOR' : _TRANSRESPONSEMESG,
  '__module__' : 'protos.transresponsemesg_pb2'
  # @@protoc_insertion_point(class_scope:TransResponseMesg)
  })
_sym_db.RegisterMessage(TransResponseMesg)


# @@protoc_insertion_point(module_scope)
