# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/transrequestmesg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/transrequestmesg.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dprotos/transrequestmesg.proto\"#\n\x10TransRequestMesg\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x62\x06proto3'
)




_TRANSREQUESTMESG = _descriptor.Descriptor(
  name='TransRequestMesg',
  full_name='TransRequestMesg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='TransRequestMesg.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['TransRequestMesg'] = _TRANSREQUESTMESG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransRequestMesg = _reflection.GeneratedProtocolMessageType('TransRequestMesg', (_message.Message,), {
  'DESCRIPTOR' : _TRANSREQUESTMESG,
  '__module__' : 'protos.transrequestmesg_pb2'
  # @@protoc_insertion_point(class_scope:TransRequestMesg)
  })
_sym_db.RegisterMessage(TransRequestMesg)


# @@protoc_insertion_point(module_scope)
