# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import transrequestmesg_pb2 as protos_dot_transrequestmesg__pb2
from protos import transresponsemesg_pb2 as protos_dot_transresponsemesg__pb2


class TransactionServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getBalance = channel.unary_unary(
                '/TransactionServices/getBalance',
                request_serializer=protos_dot_transrequestmesg__pb2.TransRequestMesg.SerializeToString,
                response_deserializer=protos_dot_transresponsemesg__pb2.TransResponseMesg.FromString,
                )


class TransactionServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.getBalance,
                    request_deserializer=protos_dot_transrequestmesg__pb2.TransRequestMesg.FromString,
                    response_serializer=protos_dot_transresponsemesg__pb2.TransResponseMesg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TransactionServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransactionServices(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TransactionServices/getBalance',
            protos_dot_transrequestmesg__pb2.TransRequestMesg.SerializeToString,
            protos_dot_transresponsemesg__pb2.TransResponseMesg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
